context:
  version: "1.0.9"

package:
  name: libgbm
  version: ${{ version }}

source:
  url: https://github.com/glfs-book/libgbm/archive/refs/tags/${{ version }}.tar.gz
  sha256: cb11e7d2aa28da8818606dc784d8034da4c052d260b5eca65b24fbf8cf7d8f60

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - meson
    - pkg-config
  host:
    - libdrm
  run_exports:
    - ${{ pin_subpackage('libgbm', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - gbm.h
      lib:
        - gbm

about:
  homepage: https://github.com/glfs-book/libgbm
  license: MIT
  license_file: LICENSE
  summary: Generic Buffer Management backend loader

extra:
  recipe-maintainers:
    - jschueller
